url: http://hannahanddennis.com/
baseurl: ''

# Site settings
title: "Hannah & Dennis"
email: dennisandhannah@gmail.com
description: "Hannah Redmond and Dennis Kliban are getting married in Raleigh, NC on October 13,
2018"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3dbbf0
  secondary: 2f90b9  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/apretz

# Build settings
markdown: kramdown
permalink: pretty